### ISSUE TITLE
[BUG]: karavi-observability helm chart: there is no reference to a branching strategy or helm chart changes

### ISSUE THREAD

**Issue by gallacher** [dell/karavi-observability#16]
**Describe the bug**
The branching strategy for Karavi Observability is linked to from here: https://github.com/dell/helm-charts/blob/main/charts/karavi-observability/VERSIONING.md.  This link does not point to the correct section in the CONTRIBUTING.md file at the root of the helm-charts repository.  Instead, it should point here: https://github.com/dell/helm-charts/blob/main/docs/CONTRIBUTING.md#branching-strategy.

In addition to this, the branching strategy listed in https://github.com/dell/helm-charts/blob/main/docs/CONTRIBUTING.md#branching-strategy is not correct.  It needs to be clearly stated that merges to the main branch will create a new release/version of the helm chart.  So if changes are being done as part of a feature, the feature should be completed in its entirety on a feature branch before being merged to main.

**To Reproduce**
N/A

**Expected behavior**
See above

**Screenshots**
N/A

**Logs**
N/A

**System Information (please complete the following information):**
N/A

**Additional context**
Documentation change to the karavi-observability helm chart in github.com/dell/helm-charts

**Comment by ioeicicdsvc** [comment]
link: 2405

**Comment by gallacher** [comment]
Issues has been fixed
