### ISSUE TITLE
[BUG]: Inadvertently exposing metrics data

### ISSUE THREAD

**Issue by gallacher** [dell/karavi-observability#23]
**Describe the bug**
The default Helm chart deployment is inadvertently exposing metrics data.

**To Reproduce**
1. Deploy Karavi Observability via the Helm chart (karavi-observability-0.2.0)
2. Metrics endpoint is exposed external to the cluster

**Expected behavior**
The metrics endpoint is not accessible outside of the Kubernetes cluster

**System Information (please complete the following information):**
 - Kubernetes Version: 1.18
 - karavi-metrics-powerflex Version: 0.2.0-pre-release
 - karavi-topology Version: 0.2.0-pre-release
 - Helm chart version: karavi-observability-0.2.0

**Comment by LJ-Software** [comment]
Resolved with release 0.2.1
