### ISSUE TITLE
[FEATURE]: Documentation Readiness

### ISSUE THREAD

**Issue by gallacher** [dell/karavi-observability#28]
As a Karavi user
I want complete, accurate, and well organized documentation 
So that I easily navigate and understand how to use and contribute to each Karavi Observability component

- Ensure the GitHub documentation for Karavi across the following repositories follows standards, is well structured, and well organized:
  - https://github.com/dell/karavi-observability
  - https://github.com/dell/karavi-metrics-powerflex
  - https://github.com/dell/karavi-topology
  - https://github.com/dell/helm-charts

- Documentation is reviewed to ensure the following:
  - The organization of the documentation flows well
  - The format of the documentation is correct
  - Documentation standards are in place

**Comment by rsedlock1958** [comment]
This is a test comment
