### ISSUE TITLE
[BUG]: karavi-topology module reports error while working

### ISSUE THREAD

**Issue by coulof** [dell/karavi-observability#52]
**Describe the bug**
Testing karavi-observability on RKE ; I noticed the following logs on the karavi-topology module:
```
kubectl  logs  -n powerflex karavi-topology-5d4669d6dd-trzxw
2021/04/27 09:38:28 Set DriverNames to [csi-vxflexos.dellemc.com]
2021/04/28 07:15:05 http: TLS handshake error from 10.42.0.0:58450: local error: tls: bad record MAC
2021/04/28 07:16:14 http: TLS handshake error from 10.42.0.0:55311: local error: tls: bad record MAC
```

**To Reproduce**
Install the module as usual (no custom certificate plain cert-manager).

**Expected behavior**
The component should start without error or just report a warning.

**System Information (please complete the following information):**
 - OS/Version: SLES 15SP2
 - Kubernetes Version : 1.20 on RKE
 - karavi-metrics-powerflex Version: 0.3
 - karavi-topology Version: 0.3
 - Prometheus Version: 2.18.2
 - Grafana Version: 7.7

**Comment by ioeicicdsvc** [comment]
@coulof: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by ameer-jabbar** [comment]
Thanks, Florian. I was able to reproduce the error message. It's actually coming from the Go net/http library:
https://github.com/golang/go/blob/e03cca64073bd1b4704482c81061d19ab019b5cc/src/net/http/server.go#L1846

The way I reproduced this message is by trying to access the HTTPS endpoint using curl without the 'insecure' option:

```console
[root@:~]$ curl -v https://***********:31433/query
*   Trying ***********...
* TCP_NODELAY set
* Connected to *********** (***********) port 31433 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Unknown (8):
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
[root@:~]$ kl karavi karavi-topology-54bc9dc667-xqdq5
time="2021-04-29T16:33:20Z" level=info msg="setting driver names" driver_names="[csi-vxflexos.dellemc.com]"
2021/04/29 16:58:17 http: TLS handshake error from 192.168.58.128:50679: local error: tls: bad record MAC
2021/04/29 17:06:35 http: TLS handshake error from 192.168.58.128:17177: local error: tls: bad record MAC
2021/04/29 17:06:52 http: TLS handshake error from 192.168.58.128:60075: local error: tls: bad record MAC
2021/04/29 17:07:11 http: TLS handshake error from 192.168.58.128:32799: local error: tls: bad record MAC
2021/04/29 17:13:05 http: TLS handshake error from 192.168.58.128:38080: local error: tls: bad record MAC
```

If I attempted a regular HTTP request against the endpoint, I got this error back:
```console
[root@:~]$ curl -v http://***********:31433/query
*   Trying ***********...
* TCP_NODELAY set
* Connected to *********** (***********) port 31433 (#0)
> GET /query HTTP/1.1
> Host: ***********:31433
> User-Agent: curl/7.58.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad Request
<
Client sent an HTTP request to an HTTPS server.
* Closing connection 0
```

I don't think we can do much about the error message pointed to by this issue. Let me know if you have any comments.

**Comment by medegw01** [comment]
Please refer to this PR: https://github.com/dell/karavi-observability/pull/59 for bug fix
