### ISSUE TITLE
[QUESTION]: Multi-array support

### ISSUE THREAD

**Issue by TomasKohout** [dell/karavi-observability#65]
Hi,

I'd like to ask if you plan to add multiarray support for Karavi since we have 2 PowerFlex clusters and Karavi seems to read configuration right, but only takes the first item in config.

If you're not planing to support this, I'll start to work on my own implementation. :slightly_smiling_face: 

Best wishes

**Comment by gallacher** [comment]
Hi @TomasKohout.  We will be providing multi-array support for PowerFlex in the 0.4.0 milestone.  Please reference feature: https://github.com/dell/karavi-observability/issues/66.

**Comment by TomasKohout** [comment]
Ok. Thank you very much. :-) Could you tell me when do you plan to release v0.4.0?

**Comment by gallacher** [comment]
@TomasKohout, the 0.4.0 milestone is currently targeted for July 9: https://github.com/dell/karavi-observability/milestone/4

**Comment by TomasKohout** [comment]
I've created my own implementation for multiarray support. I haven't tested that config will update correctly if new one is available, but metrics are exposed correctly nor I think that DriverNames field is used correctly. :slightly_smiling_face:  I do not feel that creating PR is a good idea because of previous statements, but it could help someone to use multiarray util official implementation is available. :slightly_smiling_face:  https://github.com/TomasKohout/karavi-metrics-powerflex/tree/feature-66-multiarray-support

**Comment by gallacher** [comment]
@TomasKohout, thank you once again for your contributions! We will have a maintainer work with you directly to help drive these changes to completion.
