### ISSUE TITLE
[FEATURE]: Export metric for Powerflex which will expose how full PV is.

### ISSUE THREAD

**Issue by TomasKohout** [dell/karavi-observability#84]
Hi, :slightly_smiling_face: 

I wasn't able to find a metric which would tell me how full my Powerflex PV is. 

I know that the old VxFlex client is able to show how much space is used and it seems that it get that information from VTree API.

Sadly, goscaleio does not provide API that would return such information. Because of that we are not able to create alerts when volume is almost full.

**Comment by alikdell** [comment]
Hello Tomas,

Thanks for the feedbacks.
Capacity metrics from PowerFlex are based on storagepool for now.
We are curious to know more, why in your case the need for more granularity on capacity metrics.

Providing PV base capacity metrics are in our road map.

Thanks,
Alik

**Comment by TomasKohout** [comment]
We have a Prometheus that is using Powerflex as a PS and we want to monitor how close we are to full capacity of that PV because we don't want to get ourselves in situation where Prometheus wouldn't have enough space. 

I'm glad that it's on your roadmap. Do you have any estimation? :slightly_smiling_face:

**Comment by TomasKohout** [comment]
Seems that `kubelet_volume_stats_available_bytes` expose exactly what I need. I'm closing this request now since it's not necessary anymore.
